version: "2"

services:

### mysql
    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: "test"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "123456"
        volumes:
            - /data/work/info/mysql:/var/lib/mysql

### redis
    redis:
        image: redis
        volumes:
            - /data/work/info/redis:/data

### php-fpm5
    php-fpm5:
        # image: php:5.6-fpm
        build: ./php/php5
        volumes:
            - ./php/php5/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - /data/work/logs/php:/var/log/php
            - /data/work/projects:/www
            - ~/.ssh:/root/.ssh
        links:
            - mysql
            - redis

### php-fpm7
    php-fpm7:
        # image: php:fpm
        build: ./php/php7
        volumes:
            - ./php/php7/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - /data/work/logs/php:/var/log/php
            - /data/work/projects:/www
            - ~/.ssh:/root/.ssh
        links:
            - mysql
            - redis

### nginx
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - /data/work/etc/nginx:/etc/nginx/sites-available
            - /data/work/logs/nginx:/var/log/nginx
            - /data/work/projects:/www            
        links:
            - php-fpm5
            - php-fpm7
